### ISSUE TITLE
Feature Request: Support for 'Fn::GetAtt' -> 'Name'

### ISSUE THREAD

**Issue by javydekoning** [aws-cloudformation/aws-cloudformation-resource-providers-imagebuilder#1]
I would like to see support for retrieving the Name attribute. 

**Use-case:**  
In my pipeline I would like to always reference the latest component version. Crafting that string today is difficult because I cannot easily retrieve the 'Name' attribute. I can only fetch the full Arn, and then parse the string using intrinsic functions.

**See below example:**

```yaml
  Recipe:
    Type: "AWS::ImageBuilder::ImageRecipe"
    Properties:
      Name: !Sub ${Prefix}-recipe
      Version: "1.0.7"
      ParentImage: !Sub "arn:aws:imagebuilder:${AWS::Region}:aws:image/${BaseImage}/x.x.x"
      Components:
        - ComponentArn: !Join
            - ""
            - - !Sub arn:aws:imagebuilder:${AWS::Region}:${AWS::AccountId}:component/
              - !Select [1, !Split ["/", !Ref Component]]
              - /x.x.x
```

**Instead, I'd like it to work like this:** 

```yaml
  Recipe:
    Type: "AWS::ImageBuilder::ImageRecipe"
    Properties:
      Name: !Sub ${Prefix}-recipe
      Version: "1.0.7"
      ParentImage: !Sub "arn:aws:imagebuilder:${AWS::Region}:aws:image/${BaseImage}/x.x.x"
      Components:
        - !Sub arn:aws:imagebuilder:${AWS::Region}:${AWS::AccountId}:component/${Component.Name}/x.x.x
```

Relevant Cloudformation Documentation:

> If you specify template parameter names or resource logical IDs, such as `${InstanceTypeParameter}`, AWS CloudFormation returns the same values as if you used the Ref intrinsic function. If you specify resource attributes, such as `${MyInstance.PublicIp}`, AWS CloudFormation returns the same values as if you used the Fn::GetAtt intrinsic function. 

**Why can't I just Ref the Component?**
Because referencing a different component version requires me to update the recipe version as well because it's immutable. In Cloudformation this leads to deployment failures if I forget to increment the recipe which I don't want to do .
